### ISSUE TITLE
encodeUtf16 method produce wrong result

### ISSUE THREAD

**Issue by dingbo8128** [dart-lang/utf#11]
```dart
import 'package:utf/utf.dart' as utf;
void main() {
  var s = '😆';
  print(s.codeUnits.map((x)=>x.toRadixString(16))); //(d83d, de06)
  print(utf.encodeUtf16le(s, false).map((x)=>x.toRadixString(16))); // produce (fd, ff, fd, ff), but (d8, 3d, de, 06) is expected
}
```

**Comment by kevmoo** [comment]
@lrhn ?

**Comment by dingbo8128** [comment]
dart string is already utf16 encoded, so encode dart string to utf16 format shuold produce the same result as codeUnits() method.

**Comment by lrhn** [comment]
This particular code in `package:utf` seems to predate Dart switching from UTF-32 to UTF-16 strings. It assumes that a strings code units are code points.

I'll look into it, but the package is not really supported. It was a port of the pre-Dart 1.0 libraries which were replaced by `dart:convert`, which should allow existing code to keep running, but all new code should use `dart:convert` instead.

**Comment by dingbo8128** [comment]
Thanks for your reply. I'll have a look at  dart::convert.

**Comment by lrhn** [comment]
There is actually no UTF-16 encoding in `dart:convert` because Dart strings are already UTF-16 strings. You can get the code units simply as `string.codeUnits`.
If you want those as *bytes*, the simplest approach is probably:
```dart
Uint8List encodeUtf16(String string) => Uint16List.fromList(string.codeUnits).buffer.asUint8List();
```

**Comment by iPel** [comment]
utf16.dart
```
List<int> _stringToUtf16CodeUnits(String str) {
  return codepointsToUtf16CodeUnits(str.codeUnits);
}
```
string.dart
```
 * For a character outside the Basic Multilingual Plane (plane 0) that is
 * composed of a surrogate pair, [runes] combines the pair and returns a
 * single integer.  For example, the Unicode character for a
 * musical G-clef ('𝄞') with rune value 0x1D11E consists of a UTF-16 surrogate
 * pair: `0xD834` and `0xDD1E`. Using [codeUnits] returns the surrogate pair,
 * and using `runes` returns their combined value:
 *
 *     var clef = '\u{1D11E}';
 *     clef.codeUnits;         // [0xD834, 0xDD1E]
 *     clef.runes.toList();    // [0x1D11E]
```
The `package:utf` mistakenly using surrogate pair as combined value.
